GET http://localhost:8080/user-settings/initial
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtoYWkubHYiLCJ1c2VySWQiOiIyIiwiZnVsbE5hbWUiOiIuLi4iLCJleHAiOjE2MTQwODU5OTYsImlhdCI6MTYwODA4NTk5Nn0.UaAlJ0SQw-blz2JjbWo22q3DXTaLpMk1Oqq7P1J4hvNtfUvDNfy77kheajA1WgPR80rfX17oKhdIoV8ElDj0Xp7HPv1IUkkajQL_MXCN66wUpwdW0_EJVo5kmDmLbk7zRCBKpVmmMObrnX_YUOwHpPBj_g_CMnrhpFjFoEFyimuehvFnkykfQAlgpKdGMN34ZFXvKsyLrvzHg3k4ZtNGUH9QDxVH96jl19RdNK3xChPrLnjUDexZCDbhl0cEy2p896E_hkrv7d7RE0oB49Od8li343l7L4m9JVlfC67e4ze1lIrHEjhAdnL4BMQ5czgpfWZYOsEIV5LJGjBekyJMpQ

###

POST http://localhost:8080/user-settings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJ1c2VySWQiOiIyNDYzNjY4NTU1Nzg3Mjc1MjUzIiwiZnVsbE5hbWUiOiIuLi4iLCJleHAiOjE2MTQwODM3OTYsImlhdCI6MTYwODA4Mzc5Nn0.Vfr6f8UTPLRfqQQjW_RktkivwsWGHZrfiIlHk5djtq_XD6tSAUYhfjBsHn2rqCT0SfYzLneHQ7qYzVhIkOOfCvLwvgRbYPRhHM_-AL6vOgCTZk08VUGkomqmaHlGq79I4djhf9lAA_W69ceQiUnSJsFraQZEn-5uC3D8RW-UxqX96Gt5jZUlptlP7fRMnhc3Ug_8eEGArQ4EGTWQJJBaEE1euzAeb8gJNZNw4TlAp1rLy5Onfpn661e9L0IlJLy9o8RylGpawXzcleZgsoxNRb9iWvEK2viCwrqNw3QWUcLmXCji1FKhTALfoveQT0rtGyNwu0t2Y4MhlPmKi54H9w

{
    "branchId": 2,
    "menuPath": "system/user",
    "elementId": "abc",
    "keys": ["key1", "key2"],
    "values": ["value 1", "value 2"]
}
 
### 
GET http://localhost:8080/user-settings?key=departmentId
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJ1c2VySWQiOiIyNDYzNjY4NTU1Nzg3Mjc1MjUzIiwiZnVsbE5hbWUiOiIuLi4iLCJleHAiOjE2MTQwODM3OTYsImlhdCI6MTYwODA4Mzc5Nn0.Vfr6f8UTPLRfqQQjW_RktkivwsWGHZrfiIlHk5djtq_XD6tSAUYhfjBsHn2rqCT0SfYzLneHQ7qYzVhIkOOfCvLwvgRbYPRhHM_-AL6vOgCTZk08VUGkomqmaHlGq79I4djhf9lAA_W69ceQiUnSJsFraQZEn-5uC3D8RW-UxqX96Gt5jZUlptlP7fRMnhc3Ug_8eEGArQ4EGTWQJJBaEE1euzAeb8gJNZNw4TlAp1rLy5Onfpn661e9L0IlJLy9o8RylGpawXzcleZgsoxNRb9iWvEK2viCwrqNw3QWUcLmXCji1FKhTALfoveQT0rtGyNwu0t2Y4MhlPmKi54H9w

