GET http://localhost:8080/menu?depId=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJ1c2VySWQiOiIyNDYzNjY4NTU1Nzg3Mjc1MjUzIiwiZnVsbE5hbWUiOiIuLi4iLCJleHAiOjE2MTQwMTM3MjUsImlhdCI6MTYwODAxMzcyNX0.nVwMeSBSdqfyoXq5QYo3QyzuFYq1BJKPDKD6O88001NL2CzWL6sDNNw-0Zq0laKKN91amq4t2zFx236ee0PaqDXR8pP5XYv8QaReqVzEM1dQvaNLIN6_OW18Tiuzi83Vmt-yLl88PH5jvbFae-yaMDWGfnyGzArfhsP0BTZ8rlGQm32KyLa1_gF0JLzWZFM9FATCIU0VANl10NV-MH6ZwopzoQ1OcZN2wl1t6iyR0GC6xSsBua5MQ0Wnu8BS7n7w0m5n5PCOpjeFFRgI4M5wLZrLvthzikd-keDEsoW4qF4nAwQCyt50fGjTzHLYOUPbFInmCqj2riZNVzdc8NVwsQ