GET http://localhost:8080/menu?depId=3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtoYWkubHYiLCJ1c2VySWQiOiIyIiwiZnVsbE5hbWUiOiIuLi4iLCJleHAiOjE2MTY2NzQ1NjYsImlhdCI6MTYxMDY3NDU2Nn0.NIZd8eZZNq72C_VWgO68EwslMT_feAv4Ct9mTZ5MAQDIx6nzyBHEOm5pMqhmIsujNSQiNVNcZx5_pLubNNoYF-8_YvoyluKUlcvOmIPjDunCG1nUP-KujJPs2gWdKgIF49MJoPsZ5WA5pDiNZnBD-baQajgVrtiwnPP5xkFWCWOc2Hu4PjENUCkkf_JFYx5XxX06H4E1guKVsI5XIa5c0yakQyh4V8o0jXDNhPI3-MBznDT0umkosg3L7ctI1umSaNv82KUnxXAw0uVG06wFezayn0AiNLd9fTXs6CxKXsp75guyRsM5WEmvoC2mDstbOmycm1-I5VrGrl1rbrg_SA