GET http://localhost:8080/role-control?depId=4&menuPath=system/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtoYWkubHYiLCJ1c2VySWQiOiIyIiwiZnVsbE5hbWUiOiIuLi4iLCJleHAiOjE2MTQ2MTk1NDcsImlhdCI6MTYwODYxOTU0N30.Tg4DxhV1lbY0xRQYF8Njhpzuef7iHigNxMh41z_3qsdSpVCFvS88xcmQR8AJu9Z8Cx6CVksm8QzEM4z5TB8IiJaCtggrqwv_1fs4oZzOlxOfm49d8NMc9VDob5aoJ4r4GK2YR8DTAQlCCIRkptt05pmTTrc0-zmT_s04EagxDX7LWB5_BylVqmkx1reT4pL3btaOf03XOU7aFVBRNaNpJxMI3V4YbMhwC5D9wz57CU2Kqaa0RGWvT1grhcb32WE8_McU5T5AuQ6iufvMSbwXg1rVAtKSpPChb0oSfPuJf0a4vKS7kXPWlu_EZ7FNeenPyRKpFlrrzlU43VlABGjfwA