GET http://localhost:8080/branch?fromOrgType=1&toOrgType=10&includeDisabled=false&includeDeleted=false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtoYWkubHYiLCJ1c2VySWQiOiIyIiwiZnVsbE5hbWUiOiIuLi4iLCJleHAiOjE2MTUxMTUyNzYsImlhdCI6MTYwOTExNTI3Nn0.XLQGmiI05iUiucq6ds8cpEUQrZk1qlYMI7zAEzxCew0XA7Tt-QnmSS4lVMmXY5qkS71Jnem7Sk6t1KJvd4yVdU1kiEKf0lbJEFTs5DY6I6KxuQ64X2v54wagui582w7UkOb5KcekGcvfNMIDhLbboWSz7yyF7OixEGoDFZpzgiLVjTSLj8UI3owc6O0FDqx2hBeWARM5yCBrNY7UACqHprIsss_os7a9pytZHdPj4yyyaZ8gPAY10UU4JD6lHy8-SoOgI5YLJKuP05jGbsvvTHLU8lkm6Dy6Gxjcrcgl8pBJtytLX2peNVk3q02gmvvA_lQlH9DBzF1fjLbmJxdnTQ