GET http://localhost:8080/language
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtoYWkubHYiLCJ1c2VySWQiOiIyIiwiZnVsbE5hbWUiOiIuLi4iLCJleHAiOjE2MTQwODkzNDMsImlhdCI6MTYwODA4OTM0M30.e4NUV1Er0FMsZCG2FA0roSs-C3y7IhMIvRwzjH--EDiHR6nJ9p4x9DkwwtsiyMc4ezFnxeXHwJeFVIoZn7kEeeZTOcXqQidwmp3plC21AMmPsxmLeZXR--LufzOmvsdkFbM6wOtkPtG43nBCTikwIjBABnSPkX8K71erLLkz_ZnFvOT728iw35cWsXBYWJleG-5X2J24M61T80DXhqNqzCuq7vI7XqUg4_cs61iGcTlv7REe7D8Lp1fgm5xF-Qf9SdHHY_HqPy8Xm_0bPcQD-hOY2spgUlF_ZfOFHwh0XsdJVEprLmOI2euJOhQy56VN98o78w_nPcBOV-NoEOL8IA

